### ISSUE TITLE
spawn docker ENOENT error

### ISSUE THREAD

**Issue by CnytSntrk** [smwa/hubot-docker#1]
Hi i try to use hubot docker on Rocket.cat. But when i try to see docker ps getting an error: 
`ERROR Error: spawn docker ENOENT
hubot_1       |   at exports._errnoException (util.js:746:11)
hubot_1       |   at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
hubot_1       |   at child_process.js:1144:20
hubot_1       |   at process._tickCallback (node.js:355:11)
`

any idea to fix it ? I use it with docker compose.
- EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot-pubsub,hubot-docker

**Comment by smwa** [comment]
This hints that the hubot user can't access a file, or it doesn't exist. This is most likely the docker binary.
As the hubot user, make sure you can run `docker ps`. If not, you might need to make the binary readable and executable, running `sudo chmod 755` on it.
If you can run docker ps, and it throws a different error, about the socket, the check out this post: http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

**Comment by CnytSntrk** [comment]
thank you for feedback. The problem is hubot can't access the docker. Where i need to run sudo chmod 755 exactly ? i run hubot with docker-compose

**Comment by smwa** [comment]
Is that to say that hubot is ran inside of a docker container? If that is the case, then you'll need to switch from your current hubot image to one that has docker and hubot installed inside of it(you might need to make your own image). Then you'll need to mount the docker socket(/var/run/docker.sock) inside of that container.

This package does not expect hubot to be inside of a docker container, nor does it expect docker-compose to be used.
If you are using docker-compose, but hubot is not inside of a container, then you may edit the src/docker.coffee to call 'docker-compose' instead of 'docker'

**Comment by CnytSntrk** [comment]
Hmm thats help me alot.i got the idea thank you :)
